# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/melih/PycharmProjects/pythonProject/pythonProject/MyOtomasyon/ekle.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 680)
        MainWindow.setMinimumSize(QtCore.QSize(998, 680))
        MainWindow.setMaximumSize(QtCore.QSize(998, 680))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/Database-Inactive-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("#MainWindow{\n"
"border-image: url(:/rs/icons/pexels-dids-1382902.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"border-image: url(:/rs/icons/pexels-dids-1382902.jpg);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(540, 620, 241, 21))
        self.label.setStyleSheet("font: 75 10pt \"MS Shell Dlg 2\";")
        self.label.setText("")
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(330, 10, 661, 591))
        self.tableWidget.setRowCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.kytsilndi = QtWidgets.QLabel(self.centralwidget)
        self.kytsilndi.setGeometry(QtCore.QRect(520, 500, 301, 16))
        self.kytsilndi.setText("")
        self.kytsilndi.setObjectName("kytsilndi")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 380, 321, 81))
        self.label_5.setStyleSheet("\n"
"font: 7pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 100, 239, 247))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.eklebuton = QtWidgets.QPushButton(self.layoutWidget)
        self.eklebuton.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/ok-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.eklebuton.setIcon(icon1)
        self.eklebuton.setCheckable(False)
        self.eklebuton.setChecked(False)
        self.eklebuton.setAutoDefault(False)
        self.eklebuton.setDefault(False)
        self.eklebuton.setFlat(False)
        self.eklebuton.setObjectName("eklebuton")
        self.gridLayout.addWidget(self.eklebuton, 5, 0, 1, 1)
        self.txtsicil = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtsicil.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtsicil.setObjectName("txtsicil")
        self.gridLayout.addWidget(self.txtsicil, 0, 1, 1, 1)
        self.labeladi = QtWidgets.QLabel(self.layoutWidget)
        self.labeladi.setObjectName("labeladi")
        self.gridLayout.addWidget(self.labeladi, 1, 0, 1, 1)
        self.txtadi = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtadi.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtadi.setObjectName("txtadi")
        self.gridLayout.addWidget(self.txtadi, 1, 1, 1, 1)
        self.txtsoyadi = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtsoyadi.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.txtsoyadi.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtsoyadi.setObjectName("txtsoyadi")
        self.gridLayout.addWidget(self.txtsoyadi, 2, 1, 1, 1)
        self.labelyasi = QtWidgets.QLabel(self.layoutWidget)
        self.labelyasi.setObjectName("labelyasi")
        self.gridLayout.addWidget(self.labelyasi, 3, 0, 1, 1)
        self.silbuton = QtWidgets.QPushButton(self.layoutWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/no-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.silbuton.setIcon(icon2)
        self.silbuton.setObjectName("silbuton")
        self.gridLayout.addWidget(self.silbuton, 5, 1, 1, 1)
        self.listele_buton = QtWidgets.QPushButton(self.layoutWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/Actions-view-refresh-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.listele_buton.setIcon(icon3)
        self.listele_buton.setObjectName("listele_buton")
        self.gridLayout.addWidget(self.listele_buton, 6, 0, 1, 2)
        self.cikis = QtWidgets.QPushButton(self.layoutWidget)
        self.cikis.setObjectName("cikis")
        self.gridLayout.addWidget(self.cikis, 7, 0, 1, 2)
        self.txtcins = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtcins.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtcins.setObjectName("txtcins")
        self.gridLayout.addWidget(self.txtcins, 4, 1, 1, 1)
        self.labelsoyadi = QtWidgets.QLabel(self.layoutWidget)
        self.labelsoyadi.setObjectName("labelsoyadi")
        self.gridLayout.addWidget(self.labelsoyadi, 2, 0, 1, 1)
        self.txtyasi = QtWidgets.QLineEdit(self.layoutWidget)
        self.txtyasi.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.txtyasi.setObjectName("txtyasi")
        self.gridLayout.addWidget(self.txtyasi, 3, 1, 1, 1)
        self.labelcins = QtWidgets.QLabel(self.layoutWidget)
        self.labelcins.setObjectName("labelcins")
        self.gridLayout.addWidget(self.labelcins, 4, 0, 1, 1)
        self.labelsicil = QtWidgets.QLabel(self.layoutWidget)
        self.labelsicil.setObjectName("labelsicil")
        self.gridLayout.addWidget(self.labelsicil, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 40, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 998, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sicil"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Adi"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Soyadi"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Yasi"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cinsiyeti"))
        self.label_5.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\">(Silmek istediğiniz elemanı tablodan seçip</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600;\"> sil butonuna basmanız yeterlidir.)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:9pt; font-weight:600;\"><br /></p></body></html>"))
        self.eklebuton.setText(_translate("MainWindow", "Ekle"))
        self.labeladi.setText(_translate("MainWindow", "Adi"))
        self.labelyasi.setText(_translate("MainWindow", "Yasi"))
        self.silbuton.setText(_translate("MainWindow", "SİL"))
        self.listele_buton.setText(_translate("MainWindow", "Kayıtlı Verileri Göster / Yenile"))
        self.cikis.setText(_translate("MainWindow", "Çıkış"))
        self.labelsoyadi.setText(_translate("MainWindow", "Soyadi"))
        self.labelcins.setText(_translate("MainWindow", "Cinsiyeti"))
        self.labelsicil.setText(_translate("MainWindow", "Sicil no"))
        self.label_2.setText(_translate("MainWindow", "KULLANICI PANELİ"))

import resim_rc
